driverControls.shooterLaunchRPM = 4000.0
driverControls.indexerLaunchRPM = 1000.0
driverControls.conveyorLaunchRPM = 1000.0

driverControls.intakeRPM = 4800.0
driverControls.intakeReverseRPM = -2000.0
driverControls.conveyorReverseRPM = -200.0