robot.name = EXAMPLE-ARM

# All subsystem properties should start with the name of subsystem (for this example "intakeArm")
intakeArm.motor.subsystemChild = arm
# the motorController ("talonFX" | "sparkMax" | "sim")
intakeArm.motor.motorController = talonFX
# All motors will have an io setting
intakeArm.IOSettings.inverted = false
intakeArm.IOSettings.gearing = 100.0
intakeArm.IOSettings.drumRadiusMeters = 1.0

intakeArm.IOSettings.pid.kp = 0.0
intakeArm.IOSettings.pid.ki = 0.0
intakeArm.IOSettings.pid.kd = 0.0

# the motorController settings must match the motorController defined above (for sim not necessary)
intakeArm.talonFXSettings.id = 20
# The default current limit
intakeArm.talonFXSettings.supplyCurrentLimitAmps =  15.0 
# the limit that would take place after at current limit for the supplyCurrentLowerTimeSeconds
intakeArm.talonFXSettings.supplyCurrentLowerLimitAmps = 0.0 
# amount of seconds stalled at supplyCurrentLimitAmps before lowering to supplyCurrentLowerLimitAmps 
intakeArm.talonFXSettings.supplyCurrentLowerTimeSeconds = 0.00 

intakeArm.talonFXSettings.statorCurrentLimitAmps = 5.0
intakeArm.talonFXSettings.enableStatorCurrentLimit = true

intakeArm.talonFXSettings.peakForwardVoltage = 12
intakeArm.talonFXSettings.peakReverseVoltage = -12


# the setting for the arm must start with the name defined above
intakeArm.armSettings.minAngleInDegrees = 0.0
intakeArm.armSettings.maxAngleInDegrees = 90.0
intakeArm.armSettings.startingAngleInDegrees = 0.0
intakeArm.armSettings.targetAngleToleranceInDegrees = 1.0

intakeArm.armSettings.maxVelocityInDegreesPerSecond = 45.0
intakeArm.armSettings.maxAccelerationInDegreesPerSecondSquared = 180.0

# these values are assuming that the angle is in radians
intakeArm.armSettings.feedforward.ks = 0.0
intakeArm.armSettings.feedforward.kg = 0.0
intakeArm.armSettings.feedforward.kv = 0.0
intakeArm.armSettings.feedforward.ka = 0.0

intakeArm.armSettings.color.red = 255
intakeArm.armSettings.color.blue = 0
intakeArm.armSettings.color.green = 0

intakeArm.armSettings.DCMotor = KrakenX60
intakeArm.armSettings.simulateGravity = true
intakeArm.armSettings.armLengthInMeters = 0.61
intakeArm.armSettings.armMassInKg = 20.0

