driverControls.shooterDefaultLaunchRPM = 4000.0
driverControls.shooterOutpostLaunchRPM = 4800.0
driverControls.shooterTrenchLaunchRPM = 3600.0
driverControls.shooterAgainstHubLaunchRPM = 3000.0

driverControls.indexerLaunchRPM = 1000.0
driverControls.conveyorLaunchRPM = 1000.0

driverControls.intakeRPM = 5100.0
driverControls.intakeReverseRPM = -5100.0
driverControls.conveyorReverseRPM = -200.0