robot.name = BLUE-SHOOTER

# All subsystem properties should start with the name of subsystem (for this example "myFlywheel")
shooterFlywheel.motor.subsystemChild = flywheel
# the motorController ("talonFX" | "sparkMax" | "sim")
shooterFlywheel.motor.motorController = talonFX
# All motors will have an io setting
shooterFlywheel.IOSettings.inverted = true
shooterFlywheel.IOSettings.gearing = 1.0
shooterFlywheel.IOSettings.drumRadiusMeters = 1.0
shooterFlywheel.IOSettings.pid.kp = 0.0
shooterFlywheel.IOSettings.pid.ki = 0.0
shooterFlywheel.IOSettings.pid.kd = 0.0

# the motorController settings must match the motorController defined above (for sim not necessary)
shooterFlywheel.talonFXSettings.id = 31

# The default current limit
shooterFlywheel.talonFXSettings.supplyCurrentLimitAmps =  80.0 
# the limit that would take place after at current limit for the supplyCurrentLowerTimeSeconds
shooterFlywheel.talonFXSettings.supplyCurrentLowerLimitAmps = 30.0 
# amount of seconds stalled at supplyCurrentLimitAmps before lowering to supplyCurrentLowerLimitAmps 
shooterFlywheel.talonFXSettings.supplyCurrentLowerTimeSeconds = 1.00 

shooterFlywheel.talonFXSettings.statorCurrentLimitAmps = 0.0
shooterFlywheel.talonFXSettings.enableStatorCurrentLimit = false

shooterFlywheel.talonFXSettings.peakForwardVoltage = 12
shooterFlywheel.talonFXSettings.peakReverseVoltage = -12


# the setting for the flywheel must start with the name defined above
shooterFlywheel.flywheelSettings.maxVelocityInRPMs = 11000.0
shooterFlywheel.flywheelSettings.targetVelocityToleranceInRPMs = 100.0

# these values are assuming that the speed is in radians per seconds
shooterFlywheel.flywheelSettings.feedforward.ks = 0
shooterFlywheel.flywheelSettings.feedforward.kv = 0
shooterFlywheel.flywheelSettings.feedforward.ka = 0

shooterFlywheel.flywheelSettings.color.red = 123
shooterFlywheel.flywheelSettings.color.blue = 0
shooterFlywheel.flywheelSettings.color.green = 0

shooterFlywheel.flywheelSettings.DCMotor = KrakenX60
shooterFlywheel.flywheelSettings.moiKgMetersSquared = 0.001


# All subsystem properties should start with the name of subsystem (for this example "myFlywheel")
indexerFlywheel.motor.subsystemChild = flywheel
# the motorController ("talonFX" | "sparkMax" | "sim")
indexerFlywheel.motor.motorController = talonFX
# All motors will have an io setting
indexerFlywheel.IOSettings.inverted = false
indexerFlywheel.IOSettings.gearing = 5.0
indexerFlywheel.IOSettings.drumRadiusMeters = 1.0
indexerFlywheel.IOSettings.pid.kp = 0.0
indexerFlywheel.IOSettings.pid.ki = 0.0
indexerFlywheel.IOSettings.pid.kd = 0.0

# the motorController settings must match the motorController defined above (for sim not necessary)
indexerFlywheel.talonFXSettings.id = 30
# The default current limit
indexerFlywheel.talonFXSettings.supplyCurrentLimitAmps =  10.0 
# the limit that would take place after at current limit for the supplyCurrentLowerTimeSeconds
indexerFlywheel.talonFXSettings.supplyCurrentLowerLimitAmps = 0.0 
# amount of seconds stalled at supplyCurrentLimitAmps before lowering to supplyCurrentLowerLimitAmps 
indexerFlywheel.talonFXSettings.supplyCurrentLowerTimeSeconds = 0.00 

indexerFlywheel.talonFXSettings.statorCurrentLimitAmps = 0.0
indexerFlywheel.talonFXSettings.enableStatorCurrentLimit = false

indexerFlywheel.talonFXSettings.peakForwardVoltage = 12
indexerFlywheel.talonFXSettings.peakReverseVoltage = -12


# the setting for the flywheel must start with the name defined above
indexerFlywheel.flywheelSettings.maxVelocityInRPMs = 2000.0
indexerFlywheel.flywheelSettings.targetVelocityToleranceInRPMs = 100.0

# these values are assuming that the speed is in radians per seconds
indexerFlywheel.flywheelSettings.feedforward.ks = 0.0
indexerFlywheel.flywheelSettings.feedforward.kv = 0.0
indexerFlywheel.flywheelSettings.feedforward.ka = 0.0

indexerFlywheel.flywheelSettings.color.red = 128
indexerFlywheel.flywheelSettings.color.green = 0
indexerFlywheel.flywheelSettings.color.blue = 0

indexerFlywheel.flywheelSettings.DCMotor = KrakenX60
indexerFlywheel.flywheelSettings.moiKgMetersSquared = 0.001

