backLeft.cameraType=photon
backLeft.robotToCamera.pitchDegrees=-2.6
backLeft.robotToCamera.rollDegrees=0 
backLeft.robotToCamera.xMeters=-0.2943862794
backLeft.robotToCamera.yMeters=0.3304861818
backLeft.robotToCamera.yawDegrees=-129
backLeft.robotToCamera.zMeters=0.455517885
backLeft.settings.fps=24
backLeft.settings.resHeight=800
backLeft.settings.resWidth=1280
backRight.cameraType=photon
backRight.robotToCamera.pitchDegrees=-5.2
backRight.robotToCamera.rollDegrees=0 
backRight.robotToCamera.xMeters=-0.2943871176
backRight.robotToCamera.yMeters=-0.3304853436
backRight.robotToCamera.yawDegrees=-45
backRight.robotToCamera.zMeters=0.455517885
backRight.settings.fps=24
backRight.settings.resHeight=800
backRight.settings.resWidth=1280
conveyorFlywheel.IOSettings.drumRadiusMeters=1.0
conveyorFlywheel.IOSettings.gearing=5.0
conveyorFlywheel.IOSettings.inverted=false
conveyorFlywheel.IOSettings.pid.kd=0.0
conveyorFlywheel.IOSettings.pid.ki=0.0
conveyorFlywheel.IOSettings.pid.kp=0.0
conveyorFlywheel.flywheelSettings.DCMotor=KrakenX60
conveyorFlywheel.flywheelSettings.color.blue=240
conveyorFlywheel.flywheelSettings.color.green=32
conveyorFlywheel.flywheelSettings.color.red=160
conveyorFlywheel.flywheelSettings.feedforward.ka=0.0021866
conveyorFlywheel.flywheelSettings.feedforward.ks=0.27951
conveyorFlywheel.flywheelSettings.feedforward.kv=0.093904
conveyorFlywheel.flywheelSettings.maxVelocityInRPMs=1000.0
conveyorFlywheel.flywheelSettings.moiKgMetersSquared=0.001
conveyorFlywheel.flywheelSettings.targetVelocityToleranceInRPMs=100.0
conveyorFlywheel.motor.motorController=talonFX
conveyorFlywheel.motor.subsystemChild=conveyorFlywheel
conveyorFlywheel.talonFXSettings.enableStatorCurrentLimit=false
conveyorFlywheel.talonFXSettings.id=40
conveyorFlywheel.talonFXSettings.peakForwardVoltage=12
conveyorFlywheel.talonFXSettings.peakReverseVoltage=-12
conveyorFlywheel.talonFXSettings.statorCurrentLimitAmps=0.0
conveyorFlywheel.talonFXSettings.supplyCurrentLimitAmps=10.0 
conveyorFlywheel.talonFXSettings.supplyCurrentLowerLimitAmps=0.0 
conveyorFlywheel.talonFXSettings.supplyCurrentLowerTimeSeconds=0.00 
ctre.backLeft.driveMotorId=12
ctre.backLeft.encoderId=41
ctre.backLeft.encoderInverted=false
ctre.backLeft.encoderOffsetInRotations=0.08837890625
ctre.backLeft.steerInverted=true
ctre.backLeft.steerMotorId=13
ctre.backLeft.xPosInInches=-9.6875
ctre.backLeft.yPosInInches=9.6875
ctre.backRight.driveMotorId=14
ctre.backRight.encoderId=43
ctre.backRight.encoderInverted=false
ctre.backRight.encoderOffsetInRotations=-0.26025390625
ctre.backRight.steerInverted=true
ctre.backRight.steerMotorId=15
ctre.backRight.xPosInInches=-9.6875
ctre.backRight.yPosInInches=-9.6875
ctre.canbus.hootFilePath=./logs/example.hoot
ctre.coupleRatio=3.5714285714285716
ctre.driveClosedLoopOutput=Voltage
ctre.driveFrictionVoltage=0.2
ctre.driveGains.kd=0.0
ctre.driveGains.ki=0.0
ctre.driveGains.kp=0.1
ctre.driveGains.ks=0.0
ctre.driveGains.kv=0.124
ctre.driveGearRatio=6.746031746031747
ctre.driveInertiaInKilogramSquareMeters=0.01
ctre.driveMotorType=TalonFX_Integrated
ctre.frontLeft.driveMotorId=10
ctre.frontLeft.encoderId=42
ctre.frontLeft.encoderInverted=false
ctre.frontLeft.encoderOffsetInRotations=-0.3671875
ctre.frontLeft.steerInverted=true
ctre.frontLeft.steerMotorId=11
ctre.frontLeft.xPosInInches=9.6875
ctre.frontLeft.yPosInInches=9.6875
ctre.frontRight.driveMotorId=16
ctre.frontRight.encoderId=44
ctre.frontRight.encoderInverted=false
ctre.frontRight.encoderOffsetInRotations=-0.21484375
ctre.frontRight.steerInverted=true
ctre.frontRight.steerMotorId=17
ctre.frontRight.xPosInInches=9.6875
ctre.frontRight.yPosInInches=-9.6875
ctre.invertLeftSide=false
ctre.invertRightSide=true
ctre.pigeonId=60
ctre.slipCurrentInAmps=120.0
ctre.speedAt12VoltsInMetersPerSecond=4.58
ctre.steerClosedLoopOutput=Voltage
ctre.steerFeedbackType=FusedCANcoder
ctre.steerFrictionVoltage=0.2
ctre.steerGains.ka=0.0
ctre.steerGains.kd=0.5
ctre.steerGains.ki=0.0
ctre.steerGains.kp=100.0
ctre.steerGains.ks=0.1
ctre.steerGains.kv=2.66
ctre.steerGains.staticFeedforwardSign=UseClosedLoopSign
ctre.steerGearRatio=21.428571428571427
ctre.steerInertiaInKilogramSquareMeters=0.01
ctre.steerMotorType=TalonFX_Integrated
ctre.steerStatorCurrentLimitInAmps=60.0
ctre.wheelRadiusInInches=2
driverControls.conveyorLaunchRPM=1000.0
driverControls.conveyorReverseRPM=-200.0
driverControls.indexerLaunchRPM=1000.0
driverControls.intakeRPM=5100.0
driverControls.intakeReverseRPM=-5100.0
driverControls.shooterLaunchRPM=4000.0
frontLeft.cameraType=photon
frontLeft.robotToCamera.pitchDegrees=-5
frontLeft.robotToCamera.rollDegrees=0
frontLeft.robotToCamera.xMeters=0.2943862794
frontLeft.robotToCamera.yMeters=0.3304861818
frontLeft.robotToCamera.yawDegrees=142
frontLeft.robotToCamera.zMeters=0.455517885
frontLeft.settings.fps=24
frontLeft.settings.resHeight=800
frontLeft.settings.resWidth=1280
frontRight.cameraType=photon
frontRight.robotToCamera.pitchDegrees=-10
frontRight.robotToCamera.rollDegrees=0 
frontRight.robotToCamera.xMeters=0.2943871176
frontRight.robotToCamera.yMeters=-0.3304853436
frontRight.robotToCamera.yawDegrees=48
frontRight.robotToCamera.zMeters=0.455517885
frontRight.settings.fps=24
frontRight.settings.resHeight=800
frontRight.settings.resWidth=1280
indexerFlywheel.IOSettings.drumRadiusMeters=1.0
indexerFlywheel.IOSettings.gearing=5.0
indexerFlywheel.IOSettings.inverted=false
indexerFlywheel.IOSettings.pid.kd=0.0
indexerFlywheel.IOSettings.pid.ki=0.0
indexerFlywheel.IOSettings.pid.kp=0.0
indexerFlywheel.flywheelSettings.DCMotor=KrakenX60
indexerFlywheel.flywheelSettings.color.blue=0
indexerFlywheel.flywheelSettings.color.green=0
indexerFlywheel.flywheelSettings.color.red=128
indexerFlywheel.flywheelSettings.feedforward.ka=0.0025368
indexerFlywheel.flywheelSettings.feedforward.ks=0.27617
indexerFlywheel.flywheelSettings.feedforward.kv=0.0923
indexerFlywheel.flywheelSettings.maxVelocityInRPMs=2000.0
indexerFlywheel.flywheelSettings.moiKgMetersSquared=0.001
indexerFlywheel.flywheelSettings.targetVelocityToleranceInRPMs=100.0
indexerFlywheel.motor.motorController=talonFX
indexerFlywheel.motor.subsystemChild=flywheel
indexerFlywheel.talonFXSettings.enableStatorCurrentLimit=false
indexerFlywheel.talonFXSettings.id=30
indexerFlywheel.talonFXSettings.peakForwardVoltage=12
indexerFlywheel.talonFXSettings.peakReverseVoltage=-12
indexerFlywheel.talonFXSettings.statorCurrentLimitAmps=0.0
indexerFlywheel.talonFXSettings.supplyCurrentLimitAmps=10.0 
indexerFlywheel.talonFXSettings.supplyCurrentLowerLimitAmps=0.0 
indexerFlywheel.talonFXSettings.supplyCurrentLowerTimeSeconds=0.00 
intakeArm.IOSettings.drumRadiusMeters=1.0
intakeArm.IOSettings.gearing=100.0
intakeArm.IOSettings.inverted=false
intakeArm.IOSettings.pid.kd=0.0
intakeArm.IOSettings.pid.ki=0.0
intakeArm.IOSettings.pid.kp=0.0
intakeArm.armSettings.DCMotor=KrakenX60
intakeArm.armSettings.armLengthInMeters=0.3048
intakeArm.armSettings.armMassInKg=4.53592
intakeArm.armSettings.color.blue=0
intakeArm.armSettings.color.green=0
intakeArm.armSettings.color.red=255
intakeArm.armSettings.feedforward.ka=0.0
intakeArm.armSettings.feedforward.kg=0.0
intakeArm.armSettings.feedforward.ks=0.0
intakeArm.armSettings.feedforward.kv=0.0
intakeArm.armSettings.maxAccelerationInDegreesPerSecondSquared=40.0
intakeArm.armSettings.maxAngleInDegrees=100.0
intakeArm.armSettings.maxVelocityInDegreesPerSecond=20.0
intakeArm.armSettings.minAngleInDegrees=0.0
intakeArm.armSettings.simulateGravity=true
intakeArm.armSettings.startingAngleInDegrees=100.0
intakeArm.armSettings.targetAngleToleranceInDegrees=1.0
intakeArm.motor.motorController=talonFX
intakeArm.motor.subsystemChild=arm
intakeArm.talonFXSettings.enableStatorCurrentLimit=true
intakeArm.talonFXSettings.id=20
intakeArm.talonFXSettings.peakForwardVoltage=12
intakeArm.talonFXSettings.peakReverseVoltage=-12
intakeArm.talonFXSettings.statorCurrentLimitAmps=5.0
intakeArm.talonFXSettings.supplyCurrentLimitAmps=15.0 
intakeArm.talonFXSettings.supplyCurrentLowerLimitAmps=0.0 
intakeArm.talonFXSettings.supplyCurrentLowerTimeSeconds=0.00 
intakeFlywheel.IOSettings.drumRadiusMeters=1.0
intakeFlywheel.IOSettings.gearing=1.0
intakeFlywheel.IOSettings.inverted=true
intakeFlywheel.IOSettings.pid.kd=0.0
intakeFlywheel.IOSettings.pid.ki=0.0
intakeFlywheel.IOSettings.pid.kp=0.0
intakeFlywheel.flywheelSettings.DCMotor=KrakenX60
intakeFlywheel.flywheelSettings.color.blue=80
intakeFlywheel.flywheelSettings.color.green=222
intakeFlywheel.flywheelSettings.color.red=0
intakeFlywheel.flywheelSettings.feedforward.ka=0.00031328
intakeFlywheel.flywheelSettings.feedforward.ks=0.10563
intakeFlywheel.flywheelSettings.feedforward.kv=0.018717
intakeFlywheel.flywheelSettings.maxVelocityInRPMs=6000.0
intakeFlywheel.flywheelSettings.moiKgMetersSquared=0.001
intakeFlywheel.flywheelSettings.targetVelocityToleranceInRPMs=100.0
intakeFlywheel.motor.motorController=talonFX
intakeFlywheel.motor.subsystemChild=flywheel
intakeFlywheel.talonFXSettings.enableStatorCurrentLimit=true
intakeFlywheel.talonFXSettings.id=21
intakeFlywheel.talonFXSettings.peakForwardVoltage=12
intakeFlywheel.talonFXSettings.peakReverseVoltage=-12
intakeFlywheel.talonFXSettings.statorCurrentLimitAmps=80.0
intakeFlywheel.talonFXSettings.supplyCurrentLimitAmps=40.0 
intakeFlywheel.talonFXSettings.supplyCurrentLowerLimitAmps=30.0 
intakeFlywheel.talonFXSettings.supplyCurrentLowerTimeSeconds=1.00 
robot.drive.maxSpeedMetersPerSecond=1.0
robot.drive=ctre
robot.name=BLUE
shooterFlywheel.IOSettings.drumRadiusMeters=1.0
shooterFlywheel.IOSettings.gearing=1.0
shooterFlywheel.IOSettings.inverted=true
shooterFlywheel.IOSettings.pid.kd=0.0
shooterFlywheel.IOSettings.pid.ki=0.0
shooterFlywheel.IOSettings.pid.kp=0.0
shooterFlywheel.flywheelSettings.DCMotor=KrakenX60
shooterFlywheel.flywheelSettings.color.blue=0
shooterFlywheel.flywheelSettings.color.green=0
shooterFlywheel.flywheelSettings.color.red=123
shooterFlywheel.flywheelSettings.feedforward.ka=0.0012272
shooterFlywheel.flywheelSettings.feedforward.ks=0.11384
shooterFlywheel.flywheelSettings.feedforward.kv=0.018721
shooterFlywheel.flywheelSettings.maxVelocityInRPMs=6000.0
shooterFlywheel.flywheelSettings.moiKgMetersSquared=0.001
shooterFlywheel.flywheelSettings.targetVelocityToleranceInRPMs=100.0
shooterFlywheel.motor.motorController=talonFX
shooterFlywheel.motor.subsystemChild=flywheel
shooterFlywheel.talonFXSettings.enableStatorCurrentLimit=false
shooterFlywheel.talonFXSettings.id=31
shooterFlywheel.talonFXSettings.peakForwardVoltage=12
shooterFlywheel.talonFXSettings.peakReverseVoltage=-12
shooterFlywheel.talonFXSettings.statorCurrentLimitAmps=0.0
shooterFlywheel.talonFXSettings.supplyCurrentLimitAmps=80.0 
shooterFlywheel.talonFXSettings.supplyCurrentLowerLimitAmps=30.0 
shooterFlywheel.talonFXSettings.supplyCurrentLowerTimeSeconds=1.00 
vision.addDrivetrain=true
vision.cameras=backLeft, backRight, frontLeft, frontRight
vision.fieldlayout=k2026RebuiltAndymark
vision.settings.maximumMultiTagDistanceMeters=2.88
vision.settings.maximumSingleTagDistanceMeters=1.70
vision.settings.timestampToleranceSeconds=10
vision.settings.visionLoggingDebug=true
