robot.name = PROTOTYPING

# prototypeMotor1
prototypeMotor1.motor.motorController = sim

# prototypeMotor1: io settings
prototypeMotor1.IOSettings.inverted = false
prototypeMotor1.IOSettings.gearing = 1.0
prototypeMotor1.IOSettings.drumRadiusMeters = 1.0
prototypeMotor1.IOSettings.pid.kp = 0.0
prototypeMotor1.IOSettings.pid.ki = 0.0
prototypeMotor1.IOSettings.pid.kd = 0.0

# prototypeMotor1:the motorController settings 
prototypeMotor1.talonFX.setting.id = 00

#prototypeMotor1: flywheelsSettings
prototypeMotor1.flywheelSettings.feedforward.ks = 0.0
prototypeMotor1.flywheelSettings.feedforward.kv = 0.0

prototypeMotor1.flywheelSettings.color.red = 255
prototypeMotor1.flywheelSettings.color.blue = 0
prototypeMotor1.flywheelSettings.color.green = 0

prototypeMotor1.flywheelSettings.maxVelocityInRPMs = 6000.0
prototypeMotor1.flywheelSettings.targetVelocityToleranceInRPMs = 100.0
prototypeMotor1.flywheelSettings.DCMotor = KrakenX60
prototypeMotor1.flywheelSettings.moiKgMetersSquared = 0.001


# prototypeMotor2
prototypeMotor2.motor.motorController = sim

# prototypeMotor2: io settings
prototypeMotor2.IOSettings.inverted = false
prototypeMotor2.IOSettings.gearing = 1.0
prototypeMotor2.IOSettings.drumRadiusMeters = 1.0
prototypeMotor2.IOSettings.pid.kp = 0.0
prototypeMotor2.IOSettings.pid.ki = 0.0
prototypeMotor2.IOSettings.pid.kd = 0.0

# prototypeMotor2:the motorController settings 
prototypeMotor2.talonFX.setting.id = 00

#prototypeMotor2: flywheelsSettings
prototypeMotor2.flywheelSettings.feedforward.ks = 0.0
prototypeMotor2.flywheelSettings.feedforward.kv = 0.0

prototypeMotor2.flywheelSettings.color.red = 255
prototypeMotor2.flywheelSettings.color.blue = 0
prototypeMotor2.flywheelSettings.color.green = 0

prototypeMotor2.flywheelSettings.maxVelocityInRPMs = 6000.0
prototypeMotor2.flywheelSettings.targetVelocityToleranceInRPMs = 100.0
prototypeMotor2.flywheelSettings.DCMotor = KrakenX60
prototypeMotor2.flywheelSettings.moiKgMetersSquared = 0.001

