robot.name = RED_INTAKE

# All subsystem properties should start with the name of subsystem (for this example "myFlywheel")
topIntakeFlywheel.motor.subsystemChild = flywheel
# the motorController ("talonFX" | "sparkMax" | "sim")
topIntakeFlywheel.motor.motorController = sim
# All motors will have an io setting
topIntakeFlywheel.IOSettings.inverted = false
topIntakeFlywheel.IOSettings.gearing = 3.0
topIntakeFlywheel.IOSettings.drumRadiusMeters = 1.0
topIntakeFlywheel.IOSettings.pid.kp = 0.0
topIntakeFlywheel.IOSettings.pid.ki = 0.0
topIntakeFlywheel.IOSettings.pid.kd = 0.0

# the motorController settings must match the motorController defined above (for sim not necessary)
# myFlywheel.talonFX.setting.id = 20


# the setting for the flywheel must start with the name defined above
topIntakeFlywheel.flywheelSettings.maxVelocityInRPMs = 6000.0
topIntakeFlywheel.flywheelSettings.targetVelocityToleranceInRPMs = 100.0

# these values are assuming that the speed is in radians per seconds
topIntakeFlywheel.flywheelSettings.feedforward.ks = 0.0
topIntakeFlywheel.flywheelSettings.feedforward.kv = 0.0

topIntakeFlywheel.flywheelSettings.color.red = 227
topIntakeFlywheel.flywheelSettings.color.blue = 70
topIntakeFlywheel.flywheelSettings.color.green = 23

topIntakeFlywheel.flywheelSettings.DCMotor = KrakenX60
topIntakeFlywheel.flywheelSettings.moiKgMetersSquared = 0.001



# All subsystem properties should start with the name of subsystem (for this example "myFlywheel")
bottomIntakeFlywheel.motor.subsystemChild = flywheel
# the motorController ("talonFX" | "sparkMax" | "sim")
bottomIntakeFlywheel.motor.motorController = sim
# All motors will have an io setting
bottomIntakeFlywheel.IOSettings.inverted = false
bottomIntakeFlywheel.IOSettings.gearing = 3.0
bottomIntakeFlywheel.IOSettings.drumRadiusMeters = 1.0
bottomIntakeFlywheel.IOSettings.pid.kp = 0.0
bottomIntakeFlywheel.IOSettings.pid.ki = 0.0
bottomIntakeFlywheel.IOSettings.pid.kd = 0.0

# the motorController settings must match the motorController defined above (for sim not necessary)
# myFlywheel.talonFX.setting.id = 20


# the setting for the flywheel must start with the name defined above
bottomIntakeFlywheel.flywheelSettings.maxVelocityInRPMs = 6000.0
bottomIntakeFlywheel.flywheelSettings.targetVelocityToleranceInRPMs = 100.0

# these values are assuming that the speed is in radians per seconds
bottomIntakeFlywheel.flywheelSettings.feedforward.ks = 0.0
bottomIntakeFlywheel.flywheelSettings.feedforward.kv = 0.0

bottomIntakeFlywheel.flywheelSettings.color.red = 171
bottomIntakeFlywheel.flywheelSettings.color.blue = 52
bottomIntakeFlywheel.flywheelSettings.color.green = 12

bottomIntakeFlywheel.flywheelSettings.DCMotor = KrakenX60
bottomIntakeFlywheel.flywheelSettings.moiKgMetersSquared = 0.001

