backLeft.cameraType=photon
backLeft.robotToCamera.pitchDegrees=7.715366
backLeft.robotToCamera.rollDegrees=0 
backLeft.robotToCamera.xMeters=-0.2943862794
backLeft.robotToCamera.yMeters=0.3304861818
backLeft.robotToCamera.yawDegrees=-126
backLeft.robotToCamera.zMeters=0.455517885
backLeft.settings.fps=30
backLeft.settings.resHeight=600
backLeft.settings.resWidth=800
backRight.cameraType=photon
backRight.robotToCamera.pitchDegrees=-7.715366
backRight.robotToCamera.rollDegrees=0 
backRight.robotToCamera.xMeters=-0.2943871176
backRight.robotToCamera.yMeters=-0.3304853436
backRight.robotToCamera.yawDegrees=-32
backRight.robotToCamera.zMeters=0.455517885
backRight.settings.fps=30
backRight.settings.resHeight=600
backRight.settings.resWidth=800
bottomIntakeFlywheel.IOSettings.drumRadiusMeters=1.0
bottomIntakeFlywheel.IOSettings.gearing=3.0
bottomIntakeFlywheel.IOSettings.inverted=false
bottomIntakeFlywheel.IOSettings.pid.kd=0.0
bottomIntakeFlywheel.IOSettings.pid.ki=0.0
bottomIntakeFlywheel.IOSettings.pid.kp=0.0
bottomIntakeFlywheel.flywheelSettings.DCMotor=KrakenX60
bottomIntakeFlywheel.flywheelSettings.color.blue=128
bottomIntakeFlywheel.flywheelSettings.color.green=50
bottomIntakeFlywheel.flywheelSettings.color.red=0
bottomIntakeFlywheel.flywheelSettings.feedforward.ks=0.0
bottomIntakeFlywheel.flywheelSettings.feedforward.kv=0.0
bottomIntakeFlywheel.flywheelSettings.maxVelocityInRPMs=6000.0
bottomIntakeFlywheel.flywheelSettings.moiKgMetersSquared=0.001
bottomIntakeFlywheel.flywheelSettings.targetVelocityToleranceInRPMs=100.0
bottomIntakeFlywheel.motor.motorController=sim
bottomIntakeFlywheel.motor.subsystemChild=flywheel
conveyorFlywheel.IOSettings.drumRadiusMeters=1.0
conveyorFlywheel.IOSettings.gearing=1.0
conveyorFlywheel.IOSettings.inverted=false
conveyorFlywheel.IOSettings.pid.kd=0.0
conveyorFlywheel.IOSettings.pid.ki=0.0
conveyorFlywheel.IOSettings.pid.kp=0.0
conveyorFlywheel.flywheelSettings.DCMotor=KrakenX60
conveyorFlywheel.flywheelSettings.color.blue=240
conveyorFlywheel.flywheelSettings.color.green=32
conveyorFlywheel.flywheelSettings.color.red=160
conveyorFlywheel.flywheelSettings.feedforward.ks=0.0
conveyorFlywheel.flywheelSettings.feedforward.kv=0.0
conveyorFlywheel.flywheelSettings.maxVelocityInRPMs=6000.0
conveyorFlywheel.flywheelSettings.moiKgMetersSquared=0.001
conveyorFlywheel.flywheelSettings.targetVelocityToleranceInRPMs=100.0
conveyorFlywheel.motor.motorController=sim
conveyorFlywheel.motor.subsystemChild=conveyorFlywheel
ctre.backLeft.driveMotorId=12
ctre.backLeft.encoderId=41
ctre.backLeft.encoderInverted=false
ctre.backLeft.encoderOffsetInRotations=-0.110595703125
ctre.backLeft.steerInverted=true
ctre.backLeft.steerMotorId=13
ctre.backLeft.xPosInInches=-9.6875
ctre.backLeft.yPosInInches=9.6875
ctre.backRight.driveMotorId=14
ctre.backRight.encoderId=43
ctre.backRight.encoderInverted=false
ctre.backRight.encoderOffsetInRotations=-0.48486328125
ctre.backRight.steerInverted=true
ctre.backRight.steerMotorId=15
ctre.backRight.xPosInInches=-9.6875
ctre.backRight.yPosInInches=-9.6875
ctre.canbus.hootFilePath=./logs/example.hoot
ctre.coupleRatio=3.5714285714285716
ctre.driveClosedLoopOutput=Voltage
ctre.driveFrictionVoltage=0.2
ctre.driveGains.kd=0.0
ctre.driveGains.ki=0.0
ctre.driveGains.kp=0.1
ctre.driveGains.ks=0.0
ctre.driveGains.kv=0.124
ctre.driveGearRatio=6.746031746031747
ctre.driveInertiaInKilogramSquareMeters=0.01
ctre.driveMotorType=TalonFX_Integrated
ctre.frontLeft.driveMotorId=10
ctre.frontLeft.encoderId=42
ctre.frontLeft.encoderInverted=false
ctre.frontLeft.encoderOffsetInRotations=-0.185791015625
ctre.frontLeft.steerInverted=true
ctre.frontLeft.steerMotorId=11
ctre.frontLeft.xPosInInches=9.6875
ctre.frontLeft.yPosInInches=9.6875
ctre.frontRight.driveMotorId=16
ctre.frontRight.encoderId=44
ctre.frontRight.encoderInverted=false
ctre.frontRight.encoderOffsetInRotations=-0.260986328125
ctre.frontRight.steerInverted=true
ctre.frontRight.steerMotorId=17
ctre.frontRight.xPosInInches=9.6875
ctre.frontRight.yPosInInches=-9.6875
ctre.invertLeftSide=false
ctre.invertRightSide=true
ctre.pigeonId=60
ctre.slipCurrentInAmps=120.0
ctre.speedAt12VoltsInMetersPerSecond=4.58
ctre.steerClosedLoopOutput=Voltage
ctre.steerFeedbackType=FusedCANcoder
ctre.steerFrictionVoltage=0.2
ctre.steerGains.ka=0.0
ctre.steerGains.kd=0.5
ctre.steerGains.ki=0.0
ctre.steerGains.kp=100.0
ctre.steerGains.ks=0.1
ctre.steerGains.kv=2.66
ctre.steerGains.staticFeedforwardSign=UseClosedLoopSign
ctre.steerGearRatio=21.428571428571427
ctre.steerInertiaInKilogramSquareMeters=0.01
ctre.steerMotorType=TalonFX_Integrated
ctre.steerStatorCurrentLimitInAmps=60.0
ctre.wheelRadiusInInches=2.0
driverControls.conveyorLaunchRPM=1000.0
driverControls.conveyorReverseRPM=-200.0
driverControls.indexerLaunchRPM=1000.0
driverControls.intakeRPM=2000.0
driverControls.intakeReverseRPM=-5100.0
driverControls.shooterLaunchRPM=3666.0
frontLeft.cameraType=photon
frontLeft.robotToCamera.pitchDegrees=-3.5
frontLeft.robotToCamera.rollDegrees=0
frontLeft.robotToCamera.xMeters=0.2943862794
frontLeft.robotToCamera.yMeters=0.3304861818
frontLeft.robotToCamera.yawDegrees=142
frontLeft.robotToCamera.zMeters=0.455517885
frontLeft.settings.fps=0
frontLeft.settings.resHeight=0
frontLeft.settings.resWidth=0
frontRight.cameraType=photon
frontRight.robotToCamera.pitchDegrees=-3.5
frontRight.robotToCamera.rollDegrees=0 
frontRight.robotToCamera.yawDegrees=50
frontRight.robotToCamera.zMeters=0.455517885
frontRight.settings.fps=30
frontRight.settings.resHeight=600
frontRight.settings.resWidth=800
indexerFlywheel.IOSettings.drumRadiusMeters=1.0
indexerFlywheel.IOSettings.gearing=1.0
indexerFlywheel.IOSettings.inverted=false
indexerFlywheel.IOSettings.pid.kd=0.0
indexerFlywheel.IOSettings.pid.ki=0.0
indexerFlywheel.IOSettings.pid.kp=0.0
indexerFlywheel.flywheelSettings.DCMotor=KrakenX60
indexerFlywheel.flywheelSettings.color.blue=0
indexerFlywheel.flywheelSettings.color.green=0
indexerFlywheel.flywheelSettings.color.red=128
indexerFlywheel.flywheelSettings.feedforward.ks=0.0
indexerFlywheel.flywheelSettings.feedforward.kv=0.0
indexerFlywheel.flywheelSettings.maxVelocityInRPMs=6000.0
indexerFlywheel.flywheelSettings.moiKgMetersSquared=0.001
indexerFlywheel.flywheelSettings.targetVelocityToleranceInRPMs=100.0
indexerFlywheel.motor.motorController=sim
indexerFlywheel.motor.subsystemChild=flywheel
intakeArm.IOSettings.drumRadiusMeters=1.0
intakeArm.IOSettings.gearing=100.0
intakeArm.IOSettings.inverted=false
intakeArm.IOSettings.pid.kd=0.0
intakeArm.IOSettings.pid.ki=0.0
intakeArm.IOSettings.pid.kp=0.0
intakeArm.armSettings.DCMotor=KrakenX60
intakeArm.armSettings.armLengthInMeters=0.3048
intakeArm.armSettings.armMassInKg=4.53592
intakeArm.armSettings.color.blue=0
intakeArm.armSettings.color.green=0
intakeArm.armSettings.color.red=255
intakeArm.armSettings.feedforward.ka=0.0
intakeArm.armSettings.feedforward.kg=0.0
intakeArm.armSettings.feedforward.ks=0.0
intakeArm.armSettings.feedforward.kv=0.0
intakeArm.armSettings.maxAccelerationInDegreesPerSecondSquared=40.0
intakeArm.armSettings.maxAngleInDegrees=100.0
intakeArm.armSettings.maxVelocityInDegreesPerSecond=20.0
intakeArm.armSettings.minAngleInDegrees=0.0
intakeArm.armSettings.simulateGravity=true
intakeArm.armSettings.startingAngleInDegrees=100.0
intakeArm.armSettings.targetAngleToleranceInDegrees=1.0
intakeArm.motor.motorController=sim
intakeArm.motor.subsystemChild=arm
intakeArm.talonFXSettings.enableStatorCurrentLimit=true
intakeArm.talonFXSettings.id=20
intakeArm.talonFXSettings.peakForwardVoltage=12
intakeArm.talonFXSettings.peakReverseVoltage=-12
intakeArm.talonFXSettings.statorCurrentLimitAmps=5.0
intakeArm.talonFXSettings.supplyCurrentLimitAmps=15.0 
intakeArm.talonFXSettings.supplyCurrentLowerLimitAmps=0.0 
intakeArm.talonFXSettings.supplyCurrentLowerTimeSeconds=0.00 
robot.drive.maxSpeedMetersPerSecond=.75
robot.drive=ctre
robot.name=RED
shooterFlywheel.IOSettings.drumRadiusMeters=1.0
shooterFlywheel.IOSettings.gearing=1.0
shooterFlywheel.IOSettings.inverted=false
shooterFlywheel.IOSettings.pid.kd=0.0
shooterFlywheel.IOSettings.pid.ki=0.0
shooterFlywheel.IOSettings.pid.kp=0.0
shooterFlywheel.flywheelSettings.DCMotor=Neo550
shooterFlywheel.flywheelSettings.color.blue=0
shooterFlywheel.flywheelSettings.color.green=0
shooterFlywheel.flywheelSettings.color.red=123
shooterFlywheel.flywheelSettings.feedforward.ks=0.0
shooterFlywheel.flywheelSettings.feedforward.kv=0.0
shooterFlywheel.flywheelSettings.maxVelocityInRPMs=6000.0
shooterFlywheel.flywheelSettings.moiKgMetersSquared=0.001
shooterFlywheel.flywheelSettings.targetVelocityToleranceInRPMs=100.0
shooterFlywheel.motor.motorController=sim
shooterFlywheel.motor.subsystemChild=flywheel
topIntakeFlywheel.IOSettings.drumRadiusMeters=1.0
topIntakeFlywheel.IOSettings.gearing=3.0
topIntakeFlywheel.IOSettings.inverted=false
topIntakeFlywheel.IOSettings.pid.kd=0.0
topIntakeFlywheel.IOSettings.pid.ki=0.0
topIntakeFlywheel.IOSettings.pid.kp=0.0
topIntakeFlywheel.flywheelSettings.DCMotor=KrakenX60
topIntakeFlywheel.flywheelSettings.color.blue=70
topIntakeFlywheel.flywheelSettings.color.green=23
topIntakeFlywheel.flywheelSettings.color.red=227
topIntakeFlywheel.flywheelSettings.feedforward.ks=0.0
topIntakeFlywheel.flywheelSettings.feedforward.kv=0.0
topIntakeFlywheel.flywheelSettings.maxVelocityInRPMs=6000.0
topIntakeFlywheel.flywheelSettings.moiKgMetersSquared=0.001
topIntakeFlywheel.flywheelSettings.targetVelocityToleranceInRPMs=100.0
topIntakeFlywheel.motor.motorController=sim
topIntakeFlywheel.motor.subsystemChild=flywheel
vision.addDrivetrain=true
vision.cameras=backLeft, backRight, frontLeft, frontRight
vision.fieldlayout=k2026RebuiltAndymark
vision.settings.maximumMultiTagDistanceMeters=3.9
vision.settings.maximumSingleTagDistanceMeters=2.0
vision.settings.timestampToleranceSeconds=10
vision.settings.visionLoggingDebug=true
