bottomIntakeFlywheel.IOSettings.drumRadiusMeters=1.0
bottomIntakeFlywheel.IOSettings.gearing=3.0
bottomIntakeFlywheel.IOSettings.inverted=false
bottomIntakeFlywheel.IOSettings.pid.kd=0.0
bottomIntakeFlywheel.IOSettings.pid.ki=0.0
bottomIntakeFlywheel.IOSettings.pid.kp=0.0
bottomIntakeFlywheel.flywheelSettings.DCMotor=KrakenX60
bottomIntakeFlywheel.flywheelSettings.color.blue=128
bottomIntakeFlywheel.flywheelSettings.color.green=50
bottomIntakeFlywheel.flywheelSettings.color.red=0
bottomIntakeFlywheel.flywheelSettings.feedforward.ks=0.0
bottomIntakeFlywheel.flywheelSettings.feedforward.kv=0.0
bottomIntakeFlywheel.flywheelSettings.maxVelocityInRPMs=2000.0
bottomIntakeFlywheel.flywheelSettings.moiKgMetersSquared=0.001
bottomIntakeFlywheel.flywheelSettings.targetVelocityToleranceInRPMs=100.0
bottomIntakeFlywheel.motor.motorController=sim
bottomIntakeFlywheel.motor.subsystemChild=flywheel
conveyorFlywheel.IOSettings.drumRadiusMeters=1.0
conveyorFlywheel.IOSettings.gearing=5.0
conveyorFlywheel.IOSettings.inverted=false
conveyorFlywheel.IOSettings.pid.kd=0.0
conveyorFlywheel.IOSettings.pid.ki=0.0
conveyorFlywheel.IOSettings.pid.kp=0.0
conveyorFlywheel.flywheelSettings.DCMotor=KrakenX60
conveyorFlywheel.flywheelSettings.color.blue=240
conveyorFlywheel.flywheelSettings.color.green=32
conveyorFlywheel.flywheelSettings.color.red=160
conveyorFlywheel.flywheelSettings.feedforward.ks=0.0
conveyorFlywheel.flywheelSettings.feedforward.kv=0.0
conveyorFlywheel.flywheelSettings.maxVelocityInRPMs=1200.0
conveyorFlywheel.flywheelSettings.moiKgMetersSquared=0.001
conveyorFlywheel.flywheelSettings.targetVelocityToleranceInRPMs=100.0
conveyorFlywheel.motor.motorController=sim
conveyorFlywheel.motor.subsystemChild=flywheel
ctre.backLeft.driveMotorId=12
ctre.backLeft.encoderId=41
ctre.backLeft.encoderInverted=false
ctre.backLeft.encoderOffsetInRotations=0.012939453125
ctre.backLeft.steerInverted=true
ctre.backLeft.steerMotorId=13
ctre.backLeft.xPosInInches=-9.6875
ctre.backLeft.yPosInInches=9.6875
ctre.backRight.driveMotorId=14
ctre.backRight.encoderId=43
ctre.backRight.encoderInverted=false
ctre.backRight.encoderOffsetInRotations=-0.464111328125
ctre.backRight.steerInverted=true
ctre.backRight.steerMotorId=15
ctre.backRight.xPosInInches=-9.6875
ctre.backRight.yPosInInches=-9.6875
ctre.canbus.hootFilePath=./logs/example.hoot
ctre.coupleRatio=3.5714285714285716
ctre.driveClosedLoopOutput=Voltage
ctre.driveFrictionVoltage=0.2
ctre.driveGains.kd=0.0
ctre.driveGains.ki=0.0
ctre.driveGains.kp=0.1
ctre.driveGains.ks=0.0
ctre.driveGains.kv=0.124
ctre.driveGearRatio=6.746031746031747
ctre.driveInertiaInKilogramSquareMeters=0.01
ctre.driveMotorType=TalonFX_Integrated
ctre.frontLeft.driveMotorId=10
ctre.frontLeft.encoderId=42
ctre.frontLeft.encoderInverted=false
ctre.frontLeft.encoderOffsetInRotations=-0.3671875
ctre.frontLeft.steerInverted=true
ctre.frontLeft.steerMotorId=11
ctre.frontLeft.xPosInInches=9.6875
ctre.frontLeft.yPosInInches=9.6875
ctre.frontRight.driveMotorId=16
ctre.frontRight.encoderId=44
ctre.frontRight.encoderInverted=false
ctre.frontRight.encoderOffsetInRotations=0.08740234375
ctre.frontRight.steerInverted=true
ctre.frontRight.steerMotorId=17
ctre.frontRight.xPosInInches=9.6875
ctre.frontRight.yPosInInches=-9.6875
ctre.invertLeftSide=false
ctre.invertRightSide=true
ctre.pigeonId=60
ctre.slipCurrentInAmps=120.0
ctre.speedAt12VoltsInMetersPerSecond=4.48
ctre.steerClosedLoopOutput=Voltage
ctre.steerFeedbackType=FusedCANcoder
ctre.steerFrictionVoltage=0.2
ctre.steerGains.ka=0.0
ctre.steerGains.kd=0.5
ctre.steerGains.ki=0.0
ctre.steerGains.kp=100.0
ctre.steerGains.ks=0.1
ctre.steerGains.kv=2.66
ctre.steerGains.staticFeedforwardSign=UseClosedLoopSign
ctre.steerGearRatio=21.428571428571427
ctre.steerInertiaInKilogramSquareMeters=0.01
ctre.steerMotorType=TalonFX_Integrated
ctre.steerStatorCurrentLimitInAmps=60.0
ctre.wheelRadiusInInches=2
driverControls.conveyorLaunchRPM=3666.0;
driverControls.conveyorReverseRPM=-200.0;
driverControls.indexerLaunchRPM=3666.0;
driverControls.intakeRPM=2000.0;
driverControls.shooterLaunchRPM=3666.0;
indexerFlywheel.IOSettings.drumRadiusMeters=1.0
indexerFlywheel.IOSettings.gearing=1.0
indexerFlywheel.IOSettings.inverted=false
indexerFlywheel.IOSettings.pid.kd=0.0
indexerFlywheel.IOSettings.pid.ki=0.0
indexerFlywheel.IOSettings.pid.kp=0.0
indexerFlywheel.flywheelSettings.DCMotor=KrakenX60
indexerFlywheel.flywheelSettings.color.blue=0
indexerFlywheel.flywheelSettings.color.green=0
indexerFlywheel.flywheelSettings.color.red=128
indexerFlywheel.flywheelSettings.feedforward.ks=0.0
indexerFlywheel.flywheelSettings.feedforward.kv=0.0
indexerFlywheel.flywheelSettings.maxVelocityInRPMs=2000.0
indexerFlywheel.flywheelSettings.moiKgMetersSquared=0.001
indexerFlywheel.flywheelSettings.targetVelocityToleranceInRPMs=100.0
indexerFlywheel.motor.motorController=sim
indexerFlywheel.motor.subsystemChild=flywheel
robot.drive=ctre
robot.name=SIM
shooterFlywheel.IOSettings.drumRadiusMeters=1.0
shooterFlywheel.IOSettings.gearing=1.0
shooterFlywheel.IOSettings.inverted=false
shooterFlywheel.IOSettings.pid.kd=0.0
shooterFlywheel.IOSettings.pid.ki=0.0
shooterFlywheel.IOSettings.pid.kp=0.0
shooterFlywheel.flywheelSettings.DCMotor=Neo550
shooterFlywheel.flywheelSettings.color.blue=0
shooterFlywheel.flywheelSettings.color.green=0
shooterFlywheel.flywheelSettings.color.red=123
shooterFlywheel.flywheelSettings.feedforward.ks=0.0
shooterFlywheel.flywheelSettings.feedforward.kv=0.0
shooterFlywheel.flywheelSettings.maxVelocityInRPMs=11000.0
shooterFlywheel.flywheelSettings.moiKgMetersSquared=0.001
shooterFlywheel.flywheelSettings.targetVelocityToleranceInRPMs=100.0
shooterFlywheel.motor.motorController=sim
shooterFlywheel.motor.subsystemChild=flywheel
topIntakeFlywheel.IOSettings.drumRadiusMeters=1.0
topIntakeFlywheel.IOSettings.gearing=3.0
topIntakeFlywheel.IOSettings.inverted=false
topIntakeFlywheel.IOSettings.pid.kd=0.0
topIntakeFlywheel.IOSettings.pid.ki=0.0
topIntakeFlywheel.IOSettings.pid.kp=0.0
topIntakeFlywheel.flywheelSettings.DCMotor=KrakenX60
topIntakeFlywheel.flywheelSettings.color.blue=80
topIntakeFlywheel.flywheelSettings.color.green=222
topIntakeFlywheel.flywheelSettings.color.red=0
topIntakeFlywheel.flywheelSettings.feedforward.ks=0.0
topIntakeFlywheel.flywheelSettings.feedforward.kv=0.0
topIntakeFlywheel.flywheelSettings.maxVelocityInRPMs=2000.0
topIntakeFlywheel.flywheelSettings.moiKgMetersSquared=0.001
topIntakeFlywheel.flywheelSettings.targetVelocityToleranceInRPMs=100.0
topIntakeFlywheel.motor.motorController=sim
topIntakeFlywheel.motor.subsystemChild=flywheel
