robot.name = EXAMPLE-SIMPLE-MOTOR


mySimpleMotor.motor.subsystemChild = flywheel
# the motorController ("talonFX" | "sparkMax" | "sim")
mySimpleMotor.motor.motorController = sim
# All motors will have an io setting
mySimpleMotor.IOSettings.inverted = false
mySimpleMotor.IOSettings.gearing = 1.0
mySimpleMotor.IOSettings.drumRadiusMeters = 1.0
mySimpleMotor.IOSettings.pid.kp = 0.0
mySimpleMotor.IOSettings.pid.ki = 0.0
mySimpleMotor.IOSettings.pid.kd = 0.0

# the motorController settings must match the motorController defined above (for sim not necessary)
# myFlywheel.talonFXSettings.id = 20


# the setting for the simple motor must start with the name defined above
mySimpleMotor.simpleMotorSettings.minPositionInRads = 0
mySimpleMotor.simpleMotorSettings.maxPositionInRads = 62.8318530718
mySimpleMotor.simpleMotorSettings.startingPositionInRads = 0
mySimpleMotor.simpleMotorSettings.targetPositionToleranceInRad = 3.14159265358979323846
mySimpleMotor.simpleMotorSettings.maxVelocityInRadiansPerSecond = 6.283185307179586
mySimpleMotor.simpleMotorSettings.maxAccelerationInRadiansPerSecondSquared = 25.1327412287

# these values are assuming that the speed is in radians per second
mySimpleMotor.simpleMotorSettings.feedforward.ks = 0.0
mySimpleMotor.simpleMotorSettings.feedforward.kv = 0.0


mySimpleMotor.simpleMotorSettings.color.red = 255
mySimpleMotor.simpleMotorSettings.color.blue = 0
mySimpleMotor.simpleMotorSettings.color.green = 0

mySimpleMotor.simpleMotorSettings.DCMotor = KrakenX60
mySimpleMotor.simpleMotorSettings.moiKgMetersSquared = 0.025

