# front right
frontright.robotToCamera.xMeters = 0.3683
frontright.robotToCamera.yMeters = 0.0
frontright.robotToCamera.zMeters = 0.552831
frontright.robotToCamera.rollDegrees = 0 
frontright.robotToCamera.pitchDegrees = 5
frontright.robotToCamera.yawDegrees = 0

frontright.settings.fps = 30
frontright.settings.resWidth = 800
frontright.settings.resHeight = 600

# front left
frontleft.robotToCamera.xMeters = 0.3683
frontleft.robotToCamera.yMeters = 0.0
frontleft.robotToCamera.zMeters = 0.552831
frontleft.robotToCamera.rollDegrees = 0 
frontleft.robotToCamera.pitchDegrees = 5
frontleft.robotToCamera.yawDegrees = 0

frontleft.settings.fps = 30
frontleft.settings.resWidth = 800
frontleft.settings.resHeight = 600


# back right
backright.robotToCamera.xMeters = 0.3683
backright.robotToCamera.yMeters = 0.0
backright.robotToCamera.zMeters = 0.552831
backright.robotToCamera.rollDegrees = 0 
backright.robotToCamera.pitchDegrees = 5
backright.robotToCamera.yawDegrees = 0

backright.settings.fps = 30
backright.settings.resWidth = 800
backright.settings.resHeight = 600

# back left
backleft.robotToCamera.xMeters = 0.3683
backleft.robotToCamera.yMeters = 0.0
backleft.robotToCamera.zMeters = 0.552831
backleft.robotToCamera.rollDegrees = 0 
backleft.robotToCamera.pitchDegrees = 5
backleft.robotToCamera.yawDegrees = 0

backleft.settings.fps = 30
backleft.settings.resWidth = 800
backleft.settings.resHeight = 600