robot.name = RED-CTRE
robot.drive = ctre
robot.drive.maxSpeedMetersPerSecond = 3
robot.drive.maxAngularRateRotationsPerSecond = 0.75


#all tuner constants start with ctre
#when an value is an enum value the name mys
ctre.useDefaultDriveGains = false
ctre.useDefaultSteerGains = true


ctre.steerGains.kp = 100.0
ctre.steerGains.ki = 0.0
ctre.steerGains.kd = 0.5
ctre.steerGains.ks = 0.1
ctre.steerGains.kv = 2.66
ctre.steerGains.ka = 0.0
#when an value is an enum constant, the value must match the name of the enum constant excatly
ctre.steerGains.staticFeedforwardSign = UseClosedLoopSign

ctre.driveGains.kp = 0.1
ctre.driveGains.ki = 0.0
ctre.driveGains.kd = 0.0
ctre.driveGains.ks = 0.0
ctre.driveGains.kv = 0.124

ctre.steerClosedLoopOutput = Voltage
ctre.driveClosedLoopOutput = Voltage

ctre.steerMotorType = TalonFX_Integrated
ctre.driveMotorType = TalonFX_Integrated
ctre.steerFeedbackType = FusedCANcoder

ctre.slipCurrentInAmps = 120.0
ctre.steerStatorCurrentLimitInAmps = 60.0

# ctre.canbus.name = only if using CANivore
ctre.canbus.hootFilePath = ./logs/example.hoot

ctre.speedAt12VoltsInMetersPerSecond = 4.58
ctre.coupleRatio = 3.5714285714285716
ctre.driveGearRatio = 6.746031746031747
ctre.steerGearRatio = 21.428571428571427

ctre.wheelRadiusInInches = 2
ctre.invertLeftSide = false
ctre.invertRightSide = true

ctre.steerInertiaInKilogramSquareMeters = 0.01
ctre.driveInertiaInKilogramSquareMeters = 0.01

ctre.steerFrictionVoltage = 0.2
ctre.driveFrictionVoltage = 0.2

ctre.pigeonId = 60

ctre.frontLeft.driveMotorId = 10
ctre.frontLeft.steerMotorId = 11
ctre.frontLeft.encoderId = 42
ctre.frontLeft.encoderOffsetInRotations = 0.06689453125
ctre.frontLeft.steerInverted = true
ctre.frontLeft.encoderInverted = false
ctre.frontLeft.xPosInInches = 9.6875
ctre.frontLeft.yPosInInches = 9.6875
ctre.frontLeft.driveGains.kp = 22.593
ctre.frontLeft.driveGains.ki = 0.0
ctre.frontLeft.driveGains.kd = 0.53732
ctre.frontLeft.driveGains.ks = 0.29199
ctre.frontLeft.driveGains.kv = 0.1104
ctre.frontLeft.steerGains.kp = 47.442
ctre.frontLeft.steerGains.ki = 0.0
ctre.frontLeft.steerGains.kd = 4.289
ctre.frontLeft.steerGains.ks = 0.14967
ctre.frontLeft.steerGains.kv = 2.4368
ctre.frontLeft.steerGains.ka = 0.24866



ctre.frontRight.driveMotorId = 16
ctre.frontRight.steerMotorId = 17
ctre.frontRight.encoderId = 44
ctre.frontRight.encoderOffsetInRotations = -0.241455078125
ctre.frontRight.steerInverted = true
ctre.frontRight.encoderInverted = false
ctre.frontRight.xPosInInches = 9.6875
ctre.frontRight.yPosInInches = -9.6875
ctre.frontRight.driveGains.kp = 24.14
ctre.frontRight.driveGains.ki = 0.0
ctre.frontRight.driveGains.kd = 0.60757
ctre.frontRight.driveGains.ks = 0.27916
ctre.frontRight.driveGains.kv = 0.10742
ctre.frontRight.steerGains.kp = 69.189
ctre.frontRight.steerGains.ki = 0.0
ctre.frontRight.steerGains.kd = 6.3408
ctre.frontRight.steerGains.ks = 0.23177
ctre.frontRight.steerGains.kv = 2.4485
ctre.frontRight.steerGains.ka = 0.27511

ctre.backLeft.driveMotorId = 12
ctre.backLeft.steerMotorId = 13
ctre.backLeft.encoderId = 41
ctre.backLeft.encoderOffsetInRotations = 0.0703125
ctre.backLeft.steerInverted = true
ctre.backLeft.encoderInverted = false
ctre.backLeft.xPosInInches = -9.6875
ctre.backLeft.yPosInInches = 9.6875
ctre.backLeft.driveGains.kp = 26.688
ctre.backLeft.driveGains.ki = 0.0
ctre.backLeft.driveGains.kd = 0.72577
ctre.backLeft.driveGains.ks = 0.26267
ctre.backLeft.driveGains.kv = 0.11097
ctre.backLeft.steerGains.kp = 51.329
ctre.backLeft.steerGains.ki = 0.0
ctre.backLeft.steerGains.kd = 4.0731
ctre.backLeft.steerGains.ks = 0.28848
ctre.backLeft.steerGains.kv = 2.4215
ctre.backLeft.steerGains.ka = 0.18004

ctre.backRight.driveMotorId = 14
ctre.backRight.steerMotorId = 15
ctre.backRight.encoderId = 43
ctre.backRight.encoderOffsetInRotations = -0.36279296875
ctre.backRight.steerInverted = true
ctre.backRight.encoderInverted = false
ctre.backRight.xPosInInches = -9.6875
ctre.backRight.yPosInInches = -9.6875
ctre.backRight.driveGains.kp = 25.733
ctre.backRight.driveGains.ki = 0.0
ctre.backRight.driveGains.kd = 0.67852
ctre.backRight.driveGains.ks = 0.18698
ctre.backRight.driveGains.kv = 0.11062
ctre.backRight.steerGains.kp = 68.633
ctre.backRight.steerGains.ki = 0.0
ctre.backRight.steerGains.kd = 5.0342
ctre.backRight.steerGains.ks = 0.20057
ctre.backRight.steerGains.kv = 2.4299
ctre.backRight.steerGains.ka = 0.13047
