driverControls.shooterDefaultLaunchRPM = 3500.0
driverControls.shooterOutpostLaunchRPM = 4400.0
driverControls.shooterTrenchLaunchRPM = 3700.0
driverControls.shooterAgainstHubLaunchRPM = 3150.0
driverControls.shooterDepotLaunchRPM = 4100.0
driverControls.shooterPassRPM = 3000.0

driverControls.indexerLaunchRPM = 1000.0
driverControls.conveyorLaunchRPM = 1100.0

driverControls.indexerOutpostLaunchRPM = 500.0
driverControls.conveyorOutpostLaunchRPM = 600.0

driverControls.intakeArmVolts = 5.0

driverControls.intakeRPM = 5100.0
driverControls.intakeReverseRPM = -5100.0
driverControls.conveyorReverseRPM = -200.0
driverControls.intakeDriveSpeed = 0.6
driverControls.intakeArmWhileInakingVolts = -2.0