vision.fieldlayout = k2026RebuiltAndymark
vision.addDrivetrain = true

vision.settings.timestampToleranceSeconds = 10
vision.settings.maximumSingleTagDistanceMeters = 2.0;
vision.settings.maximumMultiTagDistanceMeters = 3.9;
vision.settings.visionLoggingDebug = true;
# name of cameras
vision.cameras = frontRight, frontLeft, backRight, backLeft

# front right
frontRight.cameraType = photon

frontRight.robotToCamera.xMeters = 0.2499398862
frontRight.robotToCamera.yMeters = 0.3304901442
frontRight.robotToCamera.zMeters = 0.4715107156
frontRight.robotToCamera.rollDegrees = 0 
frontRight.robotToCamera.pitchDegrees = 82.284634
frontRight.robotToCamera.yawDegrees = 127

frontRight.settings.fps = 30
frontRight.settings.resWidth = 800
frontRight.settings.resHeight = 600

# front left
frontLeft.cameraType = photon

frontLeft.robotToCamera.xMeters = -0.3304853436
frontLeft.robotToCamera.yMeters = 0.2943862794
frontLeft.robotToCamera.zMeters = 0.4715107156
frontLeft.robotToCamera.rollDegrees = 0 
frontLeft.robotToCamera.pitchDegrees = 82.284634
frontLeft.robotToCamera.yawDegrees = 217

frontLeft.settings.fps = 30
frontLeft.settings.resWidth = 800
frontLeft.settings.resHeight = 600


# back right
backRight.cameraType = photon

backRight.robotToCamera.xMeters = 0.3304853436
backRight.robotToCamera.yMeters = -0.2943862794
backRight.robotToCamera.zMeters = 0.461867885
backRight.robotToCamera.rollDegrees = 0 
backRight.robotToCamera.pitchDegrees = 82.284634
backRight.robotToCamera.yawDegrees = 37

backRight.settings.fps = 30
backRight.settings.resWidth = 800
backRight.settings.resHeight = 600

# back left
backLeft.cameraType = photon

backLeft.robotToCamera.xMeters = -0.2943862794
backLeft.robotToCamera.yMeters = -0.3304853436
backLeft.robotToCamera.zMeters = 0.461867885
backLeft.robotToCamera.rollDegrees = 0 
backLeft.robotToCamera.pitchDegrees = 82.284634
backLeft.robotToCamera.yawDegrees = 307

backLeft.settings.fps = 30
backLeft.settings.resWidth = 800
backLeft.settings.resHeight = 600