robot.name = RED-INTAKE

# All subsystem properties should start with the name of subsystem (for this example "myFlywheel")
intakeFlywheel.motor.subsystemChild = flywheel
# the motorController ("talonFX" | "sparkMax" | "sim")
intakeFlywheel.motor.motorController = talonFX
# All motors will have an io setting
intakeFlywheel.IOSettings.inverted = true
intakeFlywheel.IOSettings.gearing = 1.0
intakeFlywheel.IOSettings.drumRadiusMeters = 1.0
intakeFlywheel.IOSettings.pid.kp = 0.0
intakeFlywheel.IOSettings.pid.ki = 0.0
intakeFlywheel.IOSettings.pid.kd = 0.0

# the motorController settings must match the motorController defined above (for sim not necessary)
intakeFlywheel.talonFXSettings.id = 21

# The default current limit
intakeFlywheel.talonFXSettings.supplyCurrentLimitAmps =  40.0 
# the limit that would take place after at current limit for the supplyCurrentLowerTimeSeconds
intakeFlywheel.talonFXSettings.supplyCurrentLowerLimitAmps = 30.0 
# amount of seconds stalled at supplyCurrentLimitAmps before lowering to supplyCurrentLowerLimitAmps 
intakeFlywheel.talonFXSettings.supplyCurrentLowerTimeSeconds = 1.00 

intakeFlywheel.talonFXSettings.statorCurrentLimitAmps = 80.0
intakeFlywheel.talonFXSettings.enableStatorCurrentLimit = true

intakeFlywheel.talonFXSettings.peakForwardVoltage = 12
intakeFlywheel.talonFXSettings.peakReverseVoltage = -12


# the setting for the flywheel must start with the name defined above
intakeFlywheel.flywheelSettings.maxVelocityInRPMs = 6000.0
intakeFlywheel.flywheelSettings.targetVelocityToleranceInRPMs = 100.0

# these values are assuming that the speed is in radians per seconds
intakeFlywheel.flywheelSettings.feedforward.ks = 0.0
intakeFlywheel.flywheelSettings.feedforward.kv = 0.0
intakeFlywheel.flywheelSettings.feedforward.ka = 0.0

intakeFlywheel.flywheelSettings.color.red = 0
intakeFlywheel.flywheelSettings.color.green = 222
intakeFlywheel.flywheelSettings.color.blue = 80

intakeFlywheel.flywheelSettings.DCMotor = KrakenX60
intakeFlywheel.flywheelSettings.moiKgMetersSquared = 0.001