vision.fieldlayout = k2026RebuiltAndymark
vision.addDrivetrain = true

vision.settings.timestampToleranceSeconds = 1
vision.settings.maximumSingleTagDistanceMeters = 2.4
vision.settings.maximumMultiTagDistanceMeters = 3.9
vision.settings.visionLoggingDebug = true
# name of cameras
vision.cameras = backLeft, backRight, frontLeft, frontRight
# front right
frontRight.cameraType = photon

frontRight.robotToCamera.xMeters = 0.23906
frontRight.robotToCamera.yMeters =-0.332271
frontRight.robotToCamera.zMeters = 0.467981
frontRight.robotToCamera.rollDegrees = 0 
frontRight.robotToCamera.pitchDegrees =-7.5
frontRight.robotToCamera.yawDegrees = 41

frontRight.settings.fps = 30
frontRight.settings.resWidth = 800
frontRight.settings.resHeight = 600

# front left
frontLeft.cameraType = photon

frontLeft.robotToCamera.xMeters = 0.332349
frontLeft.robotToCamera.yMeters = 0.296255
frontLeft.robotToCamera.zMeters = 0.467895

frontLeft.robotToCamera.rollDegrees = 0
frontLeft.robotToCamera.pitchDegrees = -3.5
frontLeft.robotToCamera.yawDegrees = 133

frontLeft.settings.fps = 0
frontLeft.settings.resWidth = 0
frontLeft.settings.resHeight = 0


# back right
backRight.cameraType = photon

backRight.robotToCamera.xMeters = -0.332374
backRight.robotToCamera.yMeters = -0.296269
backRight.robotToCamera.zMeters = 0.458225
backRight.robotToCamera.rollDegrees = 0 
backRight.robotToCamera.pitchDegrees = -3.4
backRight.robotToCamera.yawDegrees = -45

backRight.settings.fps = 30
backRight.settings.resWidth = 800
backRight.settings.resHeight = 600

# back left
backLeft.cameraType = photon

backLeft.robotToCamera.xMeters = -0.296269
backLeft.robotToCamera.yMeters = 0.332374
backLeft.robotToCamera.zMeters = 0.458225
backLeft.robotToCamera.rollDegrees = 0 
backLeft.robotToCamera.pitchDegrees = -7.5
backLeft.robotToCamera.yawDegrees = 227

backLeft.settings.fps = 30
backLeft.settings.resWidth = 800
backLeft.settings.resHeight = 600