vision.fieldlayout = k2026RebuiltAndymark
vision.addDrivetrain = true

vision.settings.timestampToleranceSeconds = 10
vision.settings.maximumSingleTagDistanceMeters = 2.0
vision.settings.maximumMultiTagDistanceMeters = 3.9
vision.settings.visionLoggingDebug = true
# name of cameras
vision.cameras = frontLeft

# front right
frontRight.cameraType = photon

frontRight.robotToCamera.xMeters = 0.2499398862
frontRight.robotToCamera.yMeters = 0.3304901442
frontRight.robotToCamera.zMeters = 0.4715107156
frontRight.robotToCamera.rollDegrees = 0 
frontRight.robotToCamera.pitchDegrees = 82.284634
frontRight.robotToCamera.yawDegrees = 127

frontRight.settings.fps = 30
frontRight.settings.resWidth = 800
frontRight.settings.resHeight = 600

# front left
frontLeft.cameraType = photon

frontLeft.robotToCamera.xMeters =0
frontLeft.robotToCamera.yMeters = 0
frontLeft.robotToCamera.zMeters = 0
frontLeft.robotToCamera.rollDegrees = 0
frontLeft.robotToCamera.pitchDegrees = 0
frontLeft.robotToCamera.yawDegrees = 0

frontLeft.settings.fps = 0
frontLeft.settings.resWidth = 0
frontLeft.settings.resHeight = 0


# back right
backRight.cameraType = photon

backRight.robotToCamera.xMeters = -0.2943871176
backRight.robotToCamera.yMeters = -0.3304853436
backRight.robotToCamera.zMeters = 0.455517885
backRight.robotToCamera.rollDegrees = 0 
backRight.robotToCamera.pitchDegrees = -7.715366
backRight.robotToCamera.yawDegrees = -32

backRight.settings.fps = 30
backRight.settings.resWidth = 800
backRight.settings.resHeight = 600

# back left
backLeft.cameraType = photon

backLeft.robotToCamera.xMeters = -0.2943862794
backLeft.robotToCamera.yMeters = 0.3304861818
backLeft.robotToCamera.zMeters = 0.455517885
backLeft.robotToCamera.rollDegrees = 0 
backLeft.robotToCamera.pitchDegrees = 7.715366
backLeft.robotToCamera.yawDegrees = -126

backLeft.settings.fps = 30
backLeft.settings.resWidth = 800
backLeft.settings.resHeight = 600