robot.name = RED-CTRE
robot.drive = ctre
robot.drive.maxSpeedMetersPerSecond = 3.5
robot.drive.maxAngularRateRotationsPerSecond = 0.75


#all tuner constants start with ctre
#when an value is an enum value the name mys
ctre.steerGains.kp = 100.0
ctre.steerGains.ki = 0.0
ctre.steerGains.kd = 0.5
ctre.steerGains.ks = 0.1
ctre.steerGains.kv = 2.66
ctre.steerGains.ka = 0.0
#when an value is an enum constant, the value must match the name of the enum constant excatly
ctre.steerGains.staticFeedforwardSign = UseClosedLoopSign

ctre.driveGains.kp = 0.1
ctre.driveGains.ki = 0.0
ctre.driveGains.kd = 0.0
ctre.driveGains.ks = 0.0
ctre.driveGains.kv = 0.124

ctre.steerClosedLoopOutput = Voltage
ctre.driveClosedLoopOutput = Voltage

ctre.steerMotorType = TalonFX_Integrated
ctre.driveMotorType = TalonFX_Integrated
ctre.steerFeedbackType = FusedCANcoder

ctre.slipCurrentInAmps = 120.0
ctre.steerStatorCurrentLimitInAmps = 60.0

# ctre.canbus.name = only if using CANivore
ctre.canbus.hootFilePath = ./logs/example.hoot

ctre.speedAt12VoltsInMetersPerSecond = 4.58
ctre.coupleRatio = 3.5714285714285716
ctre.driveGearRatio = 6.746031746031747
ctre.steerGearRatio = 21.428571428571427

ctre.wheelRadiusInInches = 2
ctre.invertLeftSide = false
ctre.invertRightSide = true

ctre.steerInertiaInKilogramSquareMeters = 0.01
ctre.driveInertiaInKilogramSquareMeters = 0.01

ctre.steerFrictionVoltage = 0.2
ctre.driveFrictionVoltage = 0.2

ctre.pigeonId = 60

ctre.frontLeft.driveMotorId = 10
ctre.frontLeft.steerMotorId = 11
ctre.frontLeft.encoderId = 42
ctre.frontLeft.encoderOffsetInRotations = 0.06689453125
ctre.frontLeft.steerInverted = true
ctre.frontLeft.encoderInverted = false
ctre.frontLeft.xPosInInches = 9.6875
ctre.frontLeft.yPosInInches = 9.6875

ctre.frontRight.driveMotorId = 16
ctre.frontRight.steerMotorId = 17
ctre.frontRight.encoderId = 44
ctre.frontRight.encoderOffsetInRotations = -0.241455078125
ctre.frontRight.steerInverted = true
ctre.frontRight.encoderInverted = false
ctre.frontRight.xPosInInches = 9.6875
ctre.frontRight.yPosInInches = -9.6875

ctre.backLeft.driveMotorId = 12
ctre.backLeft.steerMotorId = 13
ctre.backLeft.encoderId = 41
ctre.backLeft.encoderOffsetInRotations = 0.0703125
ctre.backLeft.steerInverted = true
ctre.backLeft.encoderInverted = false
ctre.backLeft.xPosInInches = -9.6875
ctre.backLeft.yPosInInches = 9.6875

ctre.backRight.driveMotorId = 14
ctre.backRight.steerMotorId = 15
ctre.backRight.encoderId = 43
ctre.backRight.encoderOffsetInRotations = -0.36279296875
ctre.backRight.steerInverted = true
ctre.backRight.encoderInverted = false
ctre.backRight.xPosInInches = -9.6875
ctre.backRight.yPosInInches = -9.6875
