robot.name = EXAMPLE-ARM

# All subsystem properties should start with the name of subsystem (for this example "myArm")
myArm.motor.subsystemChild = arm
# the motorController ("talonFX" | "sparkMax" | "sim")
myArm.motor.motorController = sim
# All motors will have an io setting
myArm.IOSettings.inverted = false
myArm.IOSettings.gearing = 125.0
myArm.IOSettings.drumRadiusMeters = 1.0

myArm.IOSettings.pid.kp = 0.36677
myArm.IOSettings.pid.ki = 0.0
myArm.IOSettings.pid.kd = 0.0

# the motorController settings must match the motorController defined above (for sim not necessary)
# myArm.talonFXSettings.id = 20


# the setting for the arm must start with the name defined above
myArm.armSettings.minAngleInDegrees = 0.0
myArm.armSettings.maxAngleInDegrees = 90.0
myArm.armSettings.startingAngleInDegrees = 0.0

myArm.armSettings.maxVelocityInDegreesPerSecond = 45.0
myArm.armSettings.maxAccelerationInDegreesPerSecondSquared = 180.0

# these values are assuming that the angle is in radians
myArm.armSettings.feedforward.ks = 0.0
myArm.armSettings.feedforward.kg = 0.0
myArm.armSettings.feedforward.kv = 2.3782
myArm.armSettings.feetforward.ka = 0.026202

myArm.armSettings.color.red = 255
myArm.armSettings.color.blue = 0
myArm.armSettings.color.green = 0

myArm.armSettings.DCMotor = KrakenX60
myArm.armSettings.simulateGravity = true
myArm.armSettings.armLengthInMeters = 0.61
myArm.armSettings.armMassInKg = 20.0

