driverControls.shooterLaunchRPM = 3666.0
driverControls.indexerLaunchRPM = 1000.0
driverControls.conveyorLaunchRPM = 1000.0

driverControls.intakeRPM = 2000.0
driverControls.conveyorReverseRPM = -200.0