driverControls.shooterDefaultLaunchRPM = 3500.0
driverControls.shooterOutpostLaunchRPM = 4400.0
driverControls.shooterTrenchLaunchRPM = 3700.0
driverControls.shooterAgainstHubLaunchRPM = 3100.0
driverControls.shooterDepotLaunchRPM = 4100.0
driverControls.shooterPassRPM = 3000.0

driverControls.indexerLaunchRPM = 1000.0
driverControls.conveyorLaunchRPM = 1100.0

driverControls.indexerOutpostLaunchRPM = 500.0
driverControls.conveyorOutpostLaunchRPM = 600.0

driverControls.intakeArmVolts = 5.0

driverControls.intakeRPM = 5100.0
driverControls.intakeReverseRPM = -5100.0
driverControls.conveyorReverseRPM = -200.0
driverControls.intakeDriveSpeed = 0.6
driverControls.intakeArmWhileInakingVolts = -2.0

robot.isDefenseBot = true
driverControls.xLinearSpeed = 3.5
driverControls.aLinearSpeed = 1.0
driverControls.bLinearSpeed = 2.0
driverControls.yLinearSpeed = 4.58
driverControls.xAngularSpeed = 0.75
driverControls.aAngularSpeed = 0.25
driverControls.bAngularSpeed = 0.50
driverControls.yAngularSpeed = 1.00