vision.fieldlayout = k2026RebuiltAndymark
vision.addDrivetrain = true

vision.settings.timestampToleranceSeconds = 10
vision.settings.maximumSingleTagDistanceMeters = 1.70
vision.settings.maximumMultiTagDistanceMeters = 2.88
vision.settings.visionLoggingDebug = true
# name of cameras
# vision.cameras = backLeft, backRight, frontLeft, frontRight
# vision.cameras = backRight
# front right
frontRight.cameraType = photon

frontRight.robotToCamera.xMeters = 0.2943871176
frontRight.robotToCamera.yMeters =-0.3304853436
frontRight.robotToCamera.zMeters = 0.455517885
frontRight.robotToCamera.rollDegrees = 0 
frontRight.robotToCamera.pitchDegrees = -10
frontRight.robotToCamera.yawDegrees = 48

frontRight.settings.fps = 24
frontRight.settings.resWidth = 1280
frontRight.settings.resHeight = 800

# front left
frontLeft.cameraType = photon

frontLeft.robotToCamera.xMeters = 0.2943862794
frontLeft.robotToCamera.yMeters = 0.3304861818
frontLeft.robotToCamera.zMeters = 0.455517885

frontLeft.robotToCamera.rollDegrees = 0
frontLeft.robotToCamera.pitchDegrees = -5
frontLeft.robotToCamera.yawDegrees = 142

frontLeft.settings.fps = 24
frontLeft.settings.resWidth = 1280
frontLeft.settings.resHeight = 800


# back right
backRight.cameraType = photon

backRight.robotToCamera.xMeters = -0.2943871176
backRight.robotToCamera.yMeters = -0.3304853436
backRight.robotToCamera.zMeters = 0.455517885
backRight.robotToCamera.rollDegrees = 0 
backRight.robotToCamera.pitchDegrees = -5.2
backRight.robotToCamera.yawDegrees = -45

backRight.settings.fps = 24
backRight.settings.resWidth = 1280
backRight.settings.resHeight = 800

# back left
backLeft.cameraType = photon

backLeft.robotToCamera.xMeters = -0.2943862794
backLeft.robotToCamera.yMeters = 0.3304861818
backLeft.robotToCamera.zMeters = 0.455517885
backLeft.robotToCamera.rollDegrees = 0 
backLeft.robotToCamera.pitchDegrees = -2.6
backLeft.robotToCamera.yawDegrees = -129

backLeft.settings.fps = 24
backLeft.settings.resWidth = 1280
backLeft.settings.resHeight = 800