robot.name = BLUE-CONVEYOR

# All subsystem properties should start with the name of subsystem (for this example "myFlywheel")
conveyorFlywheel.motor.subsystemChild = conveyorFlywheel
# the motorController ("talonFX" | "sparkMax" | "sim")
conveyorFlywheel.motor.motorController = sim
# All motors will have an io setting
conveyorFlywheel.IOSettings.inverted = false
conveyorFlywheel.IOSettings.gearing = 5.0
conveyorFlywheel.IOSettings.drumRadiusMeters = 1.0
conveyorFlywheel.IOSettings.pid.kp = 0.0
conveyorFlywheel.IOSettings.pid.ki = 0.0
conveyorFlywheel.IOSettings.pid.kd = 0.0

# the motorController settings must match the motorController defined above (for sim not necessary)
conveyorFlywheel.talonFXSettings.id = 40
# The default current limit
conveyorFlywheel.talonFXSettings.supplyCurrentLimitAmps =  10.0 
# the limit that would take place after at current limit for the supplyCurrentLowerTimeSeconds
conveyorFlywheel.talonFXSettings.supplyCurrentLowerLimitAmps = 0.0 
# amount of seconds stalled at supplyCurrentLimitAmps before lowering to supplyCurrentLowerLimitAmps 
conveyorFlywheel.talonFXSettings.supplyCurrentLowerTimeSeconds = 0.00 

conveyorFlywheel.talonFXSettings.statorCurrentLimitAmps = 0.0
conveyorFlywheel.talonFXSettings.enableStatorCurrentLimit = false

conveyorFlywheel.talonFXSettings.peakForwardVoltage = 12
conveyorFlywheel.talonFXSettings.peakReverseVoltage = -12


# the setting for the flywheel must start with the name defined above
conveyorFlywheel.flywheelSettings.maxVelocityInRPMs = 1000.0
conveyorFlywheel.flywheelSettings.targetVelocityToleranceInRPMs = 100.0

# these values are assuming that the speed is in radians per seconds
conveyorFlywheel.flywheelSettings.feedforward.ks = 0.27951
conveyorFlywheel.flywheelSettings.feedforward.kv = 0.093904
conveyorFlywheel.flywheelSettings.feedforward.ka = 0.0021866

conveyorFlywheel.flywheelSettings.color.red = 160
conveyorFlywheel.flywheelSettings.color.green = 32
conveyorFlywheel.flywheelSettings.color.blue = 240

conveyorFlywheel.flywheelSettings.DCMotor = KrakenX60
conveyorFlywheel.flywheelSettings.moiKgMetersSquared = 0.001

